# Generated by Django 2.2.3 on 2019-07-12 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGuild',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Guild id, discord')),
                ('name', models.CharField(max_length=256, verbose_name='Name of server')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of adding the guild')),
                ('mod_role', models.CharField(default=None, max_length=512, null=True, verbose_name='Role id of mods')),
                ('log_channel', models.IntegerField(default=None, null=True, verbose_name='Channel for logging')),
                ('show_updates', models.BooleanField(default=True, verbose_name='Show updates in logchannel')),
                ('run', models.BooleanField(default=False, verbose_name='Bot running for guild')),
                ('prefix', models.CharField(default=';', max_length=10, verbose_name='Prefix for guild')),
            ],
        ),
        migrations.CreateModel(
            name='UserIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User id that should be ignored in messages')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_string', models.CharField(max_length=512, verbose_name='Command string that was executed')),
                ('error_type', models.CharField(max_length=64, verbose_name='Error type')),
                ('error', models.CharField(max_length=1024, verbose_name='Error string')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of error.')),
                ('traceback', models.CharField(default=None, max_length=5000, null=True, verbose_name='Traceback of error')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_db.BaseGuild', verbose_name='Guild where error happened')),
            ],
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(verbose_name='User id, discord')),
                ('d_name', models.CharField(default='', max_length=64, verbose_name='Name on server')),
                ('g_mod', models.BooleanField(default=False, verbose_name='Mod flag')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_db.BaseGuild', verbose_name='ID of server')),
            ],
            options={
                'unique_together': {('d_id', 'g')},
            },
        ),
    ]
