# Generated by Django 2.2.3 on 2019-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Flag if user is a bot'),
        ),
    ]
