# Generated by Django 2.2.3 on 2020-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0002_baseuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='money_card_background',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='Money url of imgur'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='value_card_background',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='Value url of imgur'),
        ),
    ]
