# Generated by Django 2.2.3 on 2020-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0003_auto_20200502_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='base_role_reached',
            field=models.BooleanField(default=False, verbose_name='Base role reached'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='first_joined',
            field=models.DateTimeField(default=None, null=True, verbose_name='First joined time and date'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_joined',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last time the user joined'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='leave_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Leave time of the user'),
        ),
    ]
