# Generated by Django 2.2.3 on 2020-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0006_baseuser_bingo_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='active_user',
            field=models.BooleanField(default=False, verbose_name='Flags this user as active'),
        ),
    ]
