# Generated by Django 2.2.3 on 2020-07-26 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0007_baseuser_active_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='Name of the milestone')),
                ('last_reached', models.DateTimeField(default=None, null=True, verbose_name='When this milestone was last reached')),
                ('nr', models.FloatField(verbose_name='Number that has been reached with this milestone.')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last checked time for milestone')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_db.BaseGuild', verbose_name='Guild this belongs to')),
            ],
        ),
    ]
