# Generated by Django 2.2.3 on 2020-08-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0008_milestonedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonedata',
            name='last_milestone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_db.MilestoneData', verbose_name='Last milestone this was reached'),
        ),
        migrations.AddField(
            model_name='milestonedata',
            name='u',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_db.BaseUser', verbose_name='User that reached this milestone'),
        ),
    ]
