# Generated by Django 2.2.3 on 2020-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0009_auto_20200802_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonedata',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name of the milestone'),
        ),
    ]
