# Generated by Django 2.2.3 on 2020-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0011_auto_20200816_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='traceback',
            field=models.CharField(default=None, max_length=15000, null=True, verbose_name='Traceback of error'),
        ),
    ]
