# Generated by Django 2.2.3 on 2020-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0014_auto_20200915_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Marks that this user has been notified'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='notify_upvote',
            field=models.BooleanField(default=False, verbose_name='Marks this as a user who wants to be reminded to upvote'),
        ),
    ]
