# Generated by Django 2.2.3 on 2020-12-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_db', '0015_auto_20200917_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonedata',
            name='g',
        ),
        migrations.RemoveField(
            model_name='milestonedata',
            name='last_milestone',
        ),
        migrations.RemoveField(
            model_name='milestonedata',
            name='u',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='MilestoneData',
        ),
    ]
